import './globals.css';
import { Roboto } from 'next/font/google';
import { Toaster } from "@/components/ui/toaster";
import Navbar from '@/components/Navbar';
import getCurrentUser from '@/actions/getCurrentUser';

const roboto = Roboto({ subsets: ['latin'], weight: "400" })

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default async function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {
	const currentUser = await getCurrentUser();

	return (
		<html lang="en">
			<body className={roboto.className}>
				<Navbar currentUser={currentUser} />
				{children}
				<Toaster />
			</body>
		</html>
	)
}
